2024-11-13 10:24:55,127 - AppLogger - ERROR - Error loading JSON: 'SettingsDialog' object has no attribute 'filter_list'
2024-11-13 10:24:59,010 - AppLogger - ERROR - Error loading JSON: 'SettingsDialog' object has no attribute 'filter_list'
2024-11-13 10:49:32,937 - AppLogger - ERROR - Error loading JSON: 'SettingsDialog' object has no attribute 'get_exclusions'
2024-11-13 11:08:23,240 - AppLogger - ERROR - Error loading JSON: 'SettingsDialog' object has no attribute 'get_exclusions'
2024-11-13 11:15:55,685 - AppLogger - ERROR - Error loading JSON: 'list' object has no attribute 'items'
2024-11-13 11:17:45,793 - AppLogger - ERROR - Error loading JSON: 'list' object has no attribute 'items'
2024-11-13 11:20:33,902 - AppLogger - ERROR - Error loading JSON: 'list' object has no attribute 'items'
2024-11-13 11:22:02,435 - AppLogger - ERROR - Error loading JSON: 'list' object has no attribute 'items'
2024-11-13 11:27:13,570 - AppLogger - ERROR - sr_type_exclusions is not a dictionary.
2024-11-13 11:27:13,571 - AppLogger - ERROR - group_exclusions is not a dictionary.
2024-11-13 11:27:13,571 - AppLogger - ERROR - no_location_sr_exclusions is not a dictionary.
2024-11-13 11:27:13,571 - AppLogger - ERROR - no_location_group_exclusions is not a dictionary.
2024-11-13 11:27:13,571 - AppLogger - ERROR - no_location_included_sr_exclusions is not a dictionary.
2024-11-13 11:27:13,571 - AppLogger - ERROR - no_location_included_group_exclusions is not a dictionary.
2024-11-13 11:29:29,904 - AppLogger - ERROR - sr_type_exclusions is not a dictionary.
2024-11-13 11:29:29,904 - AppLogger - ERROR - group_exclusions is not a dictionary.
2024-11-13 11:29:29,904 - AppLogger - ERROR - no_location_sr_exclusions is not a dictionary.
2024-11-13 11:29:29,904 - AppLogger - ERROR - no_location_group_exclusions is not a dictionary.
2024-11-13 11:29:29,904 - AppLogger - ERROR - no_location_included_sr_exclusions is not a dictionary.
2024-11-13 11:29:29,904 - AppLogger - ERROR - no_location_included_group_exclusions is not a dictionary.
2024-11-13 11:53:40,995 - AppLogger - ERROR - Error loading JSON: 'SettingsDialog' object has no attribute 'populate_list_with_checkboxes'
2024-11-13 13:24:29,698 - AppLogger - ERROR - Traceback (most recent call last):
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/dialogs/settings_dialog.py", line 265, in save_settings
    'enable_no_location_included': self.no_location_include_card.isChecked(),  # Replace with actual enable checkbox reference
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SettingsDialog' object has no attribute 'no_location_include_card'
2024-11-13 13:31:34,317 - AppLogger - ERROR - Traceback (most recent call last):
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/dialogs/settings_dialog.py", line 262, in save_settings
    'enable_excluded': self.exclude_enable_checkbox.isChecked(),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isChecked'
2024-11-13 15:10:35,221 - AppLogger - ERROR - Failed to save report: name 'grand_totals' is not defined
2024-11-13 21:21:29,974 - AppLogger - ERROR - Traceback (most recent call last):
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/main_menu/settings_handler.py", line 59, in save_settings
    self.main_app.reload_stylesheet()  # Apply the new theme immediately
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'reload_stylesheet'. Did you mean: 'apply_stylesheet'?
2024-11-13 21:22:15,164 - AppLogger - ERROR - Traceback (most recent call last):
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/main_menu/settings_handler.py", line 59, in save_settings
    self.main_app.reload_stylesheet()  # Apply the new theme immediately
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'reload_stylesheet'. Did you mean: 'apply_stylesheet'?
2024-11-14 09:37:39,157 - AppLogger - ERROR - Traceback (most recent call last):
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/sr_counter/sr_counter_ui.py", line 257, in load_excel
    def load_excel(self):

KeyboardInterrupt
2024-11-14 10:37:17,113 - AppLogger - ERROR - Error during report generation: 'Month'
2024-11-14 11:47:01,625 - AppLogger - ERROR - Error generating preview: 'ReportGenerator' object has no attribute 'show_report_preview'
2024-11-14 12:37:34,418 - AppLogger - ERROR - Failed to save report: name 'total_format' is not defined
2024-11-14 12:50:06,092 - AppLogger - ERROR - Error during report generation: 'ReportGenerator' object has no attribute 'is_totals_row_present'
2024-11-14 14:03:58,585 - AppLogger - ERROR - Error during report generation: 'Jan'
2024-11-14 14:13:52,128 - AppLogger - ERROR - Error during report generation: 'Jan'
2024-11-14 14:48:02,005 - AppLogger - ERROR - Error during report generation: ReportGenerator.generate_report() got an unexpected keyword argument 'sort_by'
2024-11-14 14:53:31,551 - AppLogger - ERROR - Preview report has not been generated.
2024-11-14 14:53:38,769 - AppLogger - ERROR - Error generating preview: ReportGenerator.generate_report() got an unexpected keyword argument 'sort_by'
2024-11-14 14:54:40,220 - AppLogger - ERROR - Error generating preview: ReportGenerator.generate_report() got an unexpected keyword argument 'sort_by'
2024-11-14 15:03:07,552 - AppLogger - ERROR - Error during report generation: ReportGenerator.generate_report() got an unexpected keyword argument 'sort_by'
2024-11-14 15:05:37,416 - AppLogger - ERROR - Error during report generation: 'ReportGenerator' object has no attribute 'report_generator'
2024-11-14 15:05:37,419 - AppLogger - ERROR - Error during report generation: critical(parent: Optional[QWidget], title: Optional[str], text: Optional[str], buttons: QMessageBox.StandardButton = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'ReportGenerator'
2024-11-14 15:06:02,700 - AppLogger - ERROR - Error during report generation: 'ReportGenerator' object has no attribute 'report_generator'
2024-11-14 15:06:02,701 - AppLogger - ERROR - Error during report generation: critical(parent: Optional[QWidget], title: Optional[str], text: Optional[str], buttons: QMessageBox.StandardButton = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'ReportGenerator'
2024-11-14 15:08:31,817 - AppLogger - ERROR - Error during report generation: 'ReportGenerator' object has no attribute 'report_generator'
2024-11-14 15:08:31,819 - AppLogger - ERROR - Error during report generation: critical(parent: Optional[QWidget], title: Optional[str], text: Optional[str], buttons: QMessageBox.StandardButton = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'ReportGenerator'
2024-11-14 15:13:32,026 - AppLogger - ERROR - Traceback (most recent call last):
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/windows/main.py", line 93, in switch_to_sr_counter
    self.sr_counter = SRCounterUI(self)
                      ^^^^^^^^^^^^^^^^^
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/sr_counter/sr_counter_ui.py", line 29, in __init__
    self.report_generator = ReportGenerator(self.progress_bar)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ReportGenerator.__init__() missing 1 required positional argument: 'progress_bar'
2024-11-14 15:16:12,782 - AppLogger - ERROR - Error during report generation: 'ReportGenerator' object has no attribute 'report_generator'
2024-11-14 15:16:12,784 - AppLogger - ERROR - Error during report generation: critical(parent: Optional[QWidget], title: Optional[str], text: Optional[str], buttons: QMessageBox.StandardButton = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'ReportGenerator'
2024-11-15 08:10:07,925 - AppLogger - ERROR - Error generating report: 'Month'
2024-11-15 11:12:40,659 - AppLogger - ERROR - Error generating report: 'ReportGenerator' object has no attribute '_append_totals'
2024-11-15 13:06:53,209 - AppLogger - ERROR - Traceback (most recent call last):
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/main_menu/main_menu_ui.py", line 72, in open_settings_dialog
    dialog = SettingsHandler(main_app=self.main_window)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/main_menu/settings_handler.py", line 110, in __init__
    self.settings = AppSettings()
                    ^^^^^^^^^^^
NameError: name 'AppSettings' is not defined
2024-11-15 13:14:28,568 - AppLogger - ERROR - Traceback (most recent call last):
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/main_menu/settings_handler.py", line 70, in open_groups_dialog
    dialog = EditableTableDialog(self.groups_data, ["Group"], self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EditableTableDialog.__init__() takes from 2 to 3 positional arguments but 4 were given
2024-11-15 13:20:55,522 - AppLogger - ERROR - Traceback (most recent call last):
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/main_menu/settings_handler.py", line 57, in open_types_dialog
    dialog = EditableTableDialog(["Type"], "311_GIS_Type_Descriptions.xlsx", self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/dialogs/editable_table_dialog.py", line 19, in __init__
    self.data = self.load_data_from_excel()  # Load data on initialization
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanwybenga/Desktop/Development/COOP/Excel-Report_Generator/modules/dialogs/editable_table_dialog.py", line 69, in load_data_from_excel
    return [tuple(row) for row in data.values] if data is not None else []
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'builtin_function_or_method' object is not iterable
